- pipeline.id: phable-api-server-logs-beats
  path.config: "/usr/share/logstash/pipeline/phable.conf"
  pipeline.workers: 3

- pipeline.id: healthpe-api-server-logs-beats
  path.config: "/usr/share/logstash/pipeline/healthpe.conf"
  pipeline.workers: 3

- pipeline.id: phable-cp-api-server-logs-beats
  path.config: "/usr/share/logstash/pipeline/phable-cp.conf"
  pipeline.workers: 3


#- pipeline.id: metribeats-beats
#  path.config: "/usr/share/logstash/pipeline/metricbeat.conf"
#  queue.type: persisted
