apm-server:
  host: 0.0.0.0:8200
  rum:
    enabled: true
  auth:
    api_key:
      enabled: true
      limit: 10
  ssl:
    enabled: true
    certificate: ${CONFIG_DIR}/apm-server.crt
    key: ${CONFIG_DIR}/apm-server.key
  kibana:
    host: "https://kibana:5601"
    protocol: "https"
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    ssl:
      enabled: true
      certificate_authorities: ["${CONFIG_DIR}/ca.crt"]
      certificate: ${CONFIG_DIR}/apm-server.crt
      key: ${CONFIG_DIR}/apm-server.key

queue:
  mem:
    events: 4096
max_procs: 2

setup:
  template:
    enabled: true
    name: "phable-apm-server"
    pattern: "*-api-apm-*-*"


output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  protocol: "https"
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  ssl.certificate_authorities: ["${CONFIG_DIR}/ca.crt"]
  ssl.certificate: "${CONFIG_DIR}/apm-server.crt"
  ssl.key: "${CONFIG_DIR}/apm-server.key"
  indices:
    - index: "%{[service.name]}-api-apm-%{[service.environment]}-%{[observer.version]}-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"
    - index: "%{[service.name]}-api-apm-%{[service.environment]}-%{[observer.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"
    - index: "%{[service.name]}-api-apm-%{[service.environment]}-%{[observer.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"
    - index: "%{[service.name]}-api-apm-%{[service.environment]}-%{[observer.version]}-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "metric"
    - index: "apm-%{[observer.version]}-onboarding-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "onboarding"
    - index: "apm-%{[observer.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"
